import { Topic } from './topic';

export const TOPICS: Topic[] = [
  {
    id: 1,
    unread: 7,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 1
  },
  {
    id: 2,
    unread: 4,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 1
  },
  {
    id: 3,
    unread: 1,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 2
  },
  {
    id: 4,
    unread: 0,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 2
  },
  {
    id: 5,
    unread: 0,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 3
  },
  {
    id: 6,
    unread: 0,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 4
  },
  {
    id: 7,
    unread: 0,
    title: 'Forum post title with a complex and long question',
    // nav_string: 'Go to page: 1, 2, 3 … 7, 8, 9',
    author: 'Author name',
    date: new Date('February 4, 2016 10:13:00'),
    replies: 5,
    views: 179,
    last_author: 'Last Author name',
    last_date: new Date('April 17, 2019 12:32:00'),
    discussion_id: 5
  },
];
